const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let rows=JSON.parse(localStorage.getItem('postlyB2BRows')||'[]'), cards=[], page=0, activeId=null;
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const persist=()=>localStorage.setItem('postlyB2BRows',JSON.stringify(rows));
function renderRows(){ $('#contentRows').innerHTML=rows.length?rows.map(r=>`<tr><td><input class="pick" data-id="${r.id}" type="checkbox" ${r.selected?'checked':''}></td><td><select class="cellBiz" data-id="${r.id}"><option ${r.biz==='병원'?'selected':''}>병원</option><option ${r.biz==='변호사'?'selected':''}>변호사</option></select></td><td><input class="cellTitle" data-id="${r.id}" value="${esc(r.title)}"></td><td><input class="cellKeyword" data-id="${r.id}" value="${esc(r.keyword)}"></td><td><b>${esc(r.status||'대기')}</b></td><td><button class="secondary openRow" data-id="${r.id}">${r.cards?'열기':'원고 생성'}</button> <button class="ghost delRow" data-id="${r.id}">삭제</button></td></tr>`).join(''):'<tr><td colspan="6" style="padding:30px;text-align:center">아직 제목이 없습니다. 위에서 제목을 추가하세요.</td></tr>'; bindRows(); }
function bindRows(){ $$('.pick').forEach(x=>x.onchange=()=>{let r=rows.find(v=>v.id==x.dataset.id);r.selected=x.checked;persist()}); $$('.cellBiz').forEach(x=>x.onchange=()=>update(x,'biz')); $$('.cellTitle').forEach(x=>x.onchange=()=>update(x,'title')); $$('.cellKeyword').forEach(x=>x.onchange=()=>update(x,'keyword')); $$('.delRow').forEach(x=>x.onclick=()=>{rows=rows.filter(v=>v.id!=x.dataset.id);persist();renderRows()}); $$('.openRow').forEach(x=>x.onclick=async()=>{let r=rows.find(v=>v.id==x.dataset.id);r.cards?openEditor(r):await generate([r])}); }
function update(el,key){let r=rows.find(v=>v.id==el.dataset.id);r[key]=el.value;persist()}
$('#addRowsBtn').onclick=()=>{let ts=$('#bulkTitles').value.split(/\n+/).map(x=>x.trim()).filter(Boolean),ks=$('#bulkKeywords').value.split(/\n+/).map(x=>x.trim());if(!ts.length)return toast('제목을 입력해주세요.');ts.forEach((t,i)=>rows.push({id:Date.now()+i,biz:$('#bizType').value,title:t,keyword:ks[i]||'',status:'대기',selected:true}));persist();renderRows();$('#bulkTitles').value='';$('#bulkKeywords').value='';toast(`${ts.length}개 제목을 추가했습니다.`)};
$('#selectAllBtn').onclick=()=>{let all=!rows.every(r=>r.selected);rows.forEach(r=>r.selected=all);persist();renderRows()}; $('#generateSelectedBtn').onclick=()=>generate(rows.filter(r=>r.selected));
async function generate(list){if(!list.length)return toast('생성할 항목을 선택해주세요.');if(!window.postly)return toast('Gemini 연결은 데스크톱 앱에서 실행해주세요.');for(const r of list){if(!r.title.trim())continue;r.status='생성 중';renderRows();try{let out=await window.postly.generateAI({category:r.biz,count:1,startDate:new Date().toISOString().slice(0,10),titles:[r.title],keywords:[r.keyword],usedTopics:rows.filter(x=>x.cards&&x.id!==r.id).map(x=>x.title)});let item=out[0];r.cards=(item.cards||[]).map(c=>({k:c.kicker||'',t:c.title||'',b:c.body||''}));r.caption=item.caption||'';r.status='원고 완료';}catch(e){r.status='실패: '+e.message;}persist();renderRows();}toast('Gemini 원고 생성을 마쳤습니다.');}
function openEditor(r){activeId=r.id;cards=r.cards||[];page=0;$('#editorTitle').textContent=r.title;$('#caption').value=r.caption||'';$('#editor').classList.remove('hidden');renderCard();$('#editor').scrollIntoView({behavior:'smooth'})}
function renderCard(){if(!cards.length)return;let c=cards[page];$('#cardKicker').textContent=c.k;$('#cardTitle').textContent=c.t;$('#cardBody').textContent=c.b;$('.pageNo').textContent=`${String(page+1).padStart(2,'0')} / ${String(cards.length).padStart(2,'0')}`;$('#pageLabel').textContent=`${page+1} / ${cards.length}`;$('#kickerInput').value=c.k;$('#titleInput').value=c.t;$('#bodyInput').value=c.b;$('#thumbs').innerHTML=cards.map((x,i)=>`<button class="thumb ${i===page?'active':''}" data-page="${i}"><b>${i+1}</b><span>${esc(x.t)}</span></button>`).join('');$$('.thumb').forEach(x=>x.onclick=()=>{page=+x.dataset.page;renderCard()})}
['kickerInput','titleInput','bodyInput'].forEach((id,i)=>$('#'+id).oninput=e=>{let k=['k','t','b'][i];cards[page][k]=e.target.value;let r=rows.find(x=>x.id===activeId);r.cards=cards;persist();renderCard()}); $('#prev').onclick=()=>{page=(page-1+cards.length)%cards.length;renderCard()};$('#next').onclick=()=>{page=(page+1)%cards.length;renderCard()};
$('#captionBtn').onclick=async()=>{await navigator.clipboard.writeText($('#caption').value);toast('캡션을 복사했습니다.')}; $('#saveAllBtn').onclick=async()=>{for(let i=0;i<cards.length;i++){page=i;renderCard();await new Promise(r=>setTimeout(r,80));let canvas=await html2canvas($('#cardPreview'),{scale:1.5,useCORS:true,backgroundColor:null});let a=document.createElement('a');a.download=`postly-${activeId}-${i+1}.png`;a.href=canvas.toDataURL('image/png');a.click();}toast('카드 이미지를 저장했습니다.')};
$('#settingsBtn').onclick=async()=>{if(window.postly){let s=await window.postly.getSettings();['geminiKey','geminiModel','igUserId','graphVersion','metaToken'].forEach(k=>{if($('#'+k))$('#'+k).value=s[k]||$('#'+k).value})}$('#settingsModal').classList.remove('hidden')};$('#settingsClose').onclick=()=>$('#settingsModal').classList.add('hidden');$('#saveSettingsBtn').onclick=async()=>{if(!window.postly)return toast('데스크톱 앱에서 저장해주세요.');let old=await window.postly.getSettings();let s={...old};['geminiKey','geminiModel','igUserId','graphVersion','metaToken'].forEach(k=>s[k]=$('#'+k).value.trim());await window.postly.saveSettings(s);$('#settingsModal').classList.add('hidden');toast('연결 설정을 저장했습니다.')}; renderRows();